upstream fe_upstream {
  server fe:3000;
}

upstream api_upstream {
  server server:8000;
}

server {
  listen 80 default_server;
  server_name 166.1.161.201 _;

  client_max_body_size 50m;

  location /socket.io/ {
    proxy_pass http://api_upstream/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
  }

  location /api/ {
    proxy_pass http://api_upstream/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /storage/ {
    proxy_pass http://api_upstream/storage/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location / {
    proxy_pass http://fe_upstream/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }
}
