ALTER TABLE `Chat`
  ADD COLUMN `name` VARCHAR(191) NULL,
  ADD COLUMN `image` VARCHAR(191) NULL;

ALTER TABLE `ChatParticipant`
  ADD COLUMN `role` ENUM('OWNER', 'ADMIN', 'MEMBER') NOT NULL DEFAULT 'MEMBER';
